### ISSUE TITLE
What is train_y and val_y in dataset? 

### ISSUE THREAD

**Issue by IvanKwokKC** [CSAILVision/GazeCapture#12]
I expect both train_y and val_y are the 2D coordination of eye graze .

But the result is quite strange. Most of the coordination are very small or negative. That means most eye graze always point at the left top side. But the fact doesn't like that. Most of them are wrong.

![1](https://user-images.githubusercontent.com/39858630/58570185-1a3f2180-826a-11e9-9f13-cec7a3b8ee9e.PNG)

Please concern the circle and the center of circle. The center is the predicted point of eye gaze.

![2](https://user-images.githubusercontent.com/39858630/58570200-20cd9900-826a-11e9-8b73-903f7ac24b62.PNG)
![3](https://user-images.githubusercontent.com/39858630/58570211-24612000-826a-11e9-8bf2-5a1b47efd83d.PNG)

Somebody told me that the data was normalized, but how? How do I find the true gaze point.

**Comment by IvanKwokKC** [comment]
Somebody told me that the data was normalized.

I find the normalization function in the code:

```
def normalize(data):
    shape = data.shape
    data = np.reshape(data, (shape[0], -1))
    data = data.astype('float32') / 255. # scaling
    data = data - np.mean(data, axis=0) # normalizing
return np.reshape(data, shape)
```

I am not good in statistics. I think this is zero mean normalization.
`data = data - np.mean(data, axis=0) # normalizing`

Does it possible convert normalized data back to original one?
I have no idea.

**Comment by erkil1452** [comment]
Hi, I am not quite sure where the 'train_x' comes from. I do not think we call it that way anywhere. However, it is likely the "labelDotXCam" field which is a position on the device wrt to camera (in centimeters). That means it can be positive or negative, small or large (for iPad devices). The distribution of these values is shown in Figure 6 in The Paper.

**Comment by erkil1452** [comment]
The second question:

The data in the dataset are not normalized so you can view them directly in your favorite image viewer.

The code does normalization by dividing by 255 which is quite common for working with 8 bit images. It also does subtract the mean image (mean of the entire dataset distributed with this code). In order to view the loaded image in the Python code you have to add back this mean image. I am not sure where the snippet comes from but it is not in our code.

Our normalization code is here (from ITrackerData):

`
class SubtractMean(object):

    def __init__(self, meanImg):
        self.meanImg = transforms.ToTensor()(meanImg / 255)

    def __call__(self, tensor):
        """
        Args:
            tensor (Tensor): Tensor image of size (C, H, W) to be normalized.
        Returns:
            Tensor: Normalized image.
        """       
        return tensor.sub(self.meanImg)

`
