### ISSUE TITLE
Face Grid Arguments

### ISSUE THREAD

**Issue by Madankumar90** [CSAILVision/GazeCapture#19]
Hey,
I wanted to know what you guys are passing as arguments to get face grid values. Is Frame W/H is original image size or what values are you passing??. is Grid W/H fixed grid size 25*25?? is labelface x.y.w.h are face detection values?? Please let me know. I am stuck and perplexed in this. Thank you.

**Comment by erkil1452** [comment]
The grid is fixed size 25x25 and represents the entire image frame as taken by the camera. That means that the grid cells are often covering non-square areas of the photograph but that is fine.

**Comment by erkil1452** [comment]
And yes, labelFace should be [x,y,w,h]. Pleae refer to ITrackerData.py for usage examples.

**Comment by Madankumar90** [comment]
Thanks

**Comment by AisanSisani** [comment]
> The grid is fixed size 25x25 and represents the entire image frame as taken by the camera. That means that the grid cells are often covering non-square areas of the photograph but that is fine.

does this mean that the grid areas (pixels of value 1) always shape a square in the 25*25 grid , and basically the rectangle frame is resized to a square? 

Also since these 1 values pixels  cover non square areas, do they cover all the face pixels and cover more of the background or opposite they cover part of the face?

**Comment by erkil1452** [comment]
Yes, the face grid covers the entire image and ignores aspect. Please refer to the code for details about rounding.
