### ISSUE TITLE
Compatibility with latest iPhones 

### ISSUE THREAD

**Issue by adrienju** [CSAILVision/GazeCapture#47]
Hi and thank you for the awesome work you have done here. 

One question regarding the inference on new generation iPhones. I want to infer the model on an iPhone XR the main differences between this model and the previous version (used for the training) are the position of the camera (The camera is almost part of the screen now), and the size of the screen (6.06 inches diagonally for the XR vs 4.6 inches diagonally for the 6 ).  As a result, the output of the model is always underestimated. 

Is calibration the only answer to this issue? Or can we apply a kind of transformation to the output based on the iPhone size ? How would you tackle this problem?

Many thanks

**Comment by erkil1452** [comment]
If the issue is just the fact that the camera position and the display size differs then you can of course just shift and scale the prediction. You may call this transformation if you do it by geometrical measurements but you can also do it by collecting small sample of user data (image->prediction vs. known position where they actually look) and call it a calibration. The result should be the same but the calibration approach may also contain any other deviation coming from e.g. different color response or sharpness or lens distortion of the newer iPhone. You can perform such calibration by fine-tuning the entire network or by learning only the top layer (or maybe adding an extra layer). The latter would be more stable (prevent overfitting to the small calibration set) and mostly revert to the transformation scenario. I would go that way.
