### ISSUE TITLE
Strategy to Crop Face and Eyes

### ISSUE THREAD

**Issue by AisanSisani** [CSAILVision/GazeCapture#49]
Hello, thank you for your public source code and dataset. I want to use the model in android phone to control an application by eye movement. Thus, I need to know how did the face and eye parts are cropped in the dataset so that I can feed new samples cropped in android to the model.

**Comment by erkil1452** [comment]
Hi, we detected a face rectangle using Apple iOS face detector and then just expanded it into square as needed. I am sure there is a solution for Android as well.

**Comment by AisanSisani** [comment]
What about the eyes? Are the size of rectangles for eyes proportional to the size of the face rectangle?

**Comment by erkil1452** [comment]
In practice yes but I believe we get the rectangles already defined from the face/eye detector. I do not recall the exact iOS API and it has likely changed since then, but you can get similar eye box detections using OpenCV's Haar pipeline (though it performed worse than the iOS detector). I think you may be able to define your own crops from a library that return face key points instead such as dlib. You may need to tweak it to match the dataset but given the dataset you should be able to do that.

**Comment by AisanSisani** [comment]
in issue 3 (https://github.com/CSAILVision/GazeCapture/issues/3#issuecomment-457345998) you have mentioned that the eye square is proportional to the face squared, maybe it actually is. I could check it if I had the original dataset but due to the storage limitation I am currently using the smaller dataset where the images are already cropped and resized. Could you have a look at the original dataset and tell me the approximate scale factor if there is any?

Thank you so far for your fast replies.

**Comment by erkil1452** [comment]
I have the same hard-drive limitation when it comes to the full dataset but you should be able to compute statistics based on this file alone: https://github.com/CSAILVision/GazeCapture/blob/master/pytorch/reference_metadata.mat . It is generated by the prepareDataset.py so you can see what it contains there.
