### ISSUE TITLE
Question about the dataset split.

### ISSUE THREAD

**Issue by rioisme** [CSAILVision/GazeCapture#74]
Hi!

First of all, thanks for creating this dataset.
I have a question about the criteria of splitting the dataset(train, val, test).
GazeCapture seems to split dataset by subject. Is there any reason to this?
Will splitting GazeCapture not subject-wise(but the same data ratio) affect the benchmark score?

Thanks.

**Comment by erkil1452** [comment]
Hi, yes I think it would. If you use the same person in both training and testing, you're not testing that you have a general tracker but rather a tracker calibrated for the dataset persons. Furthermore, if you do it randomly, you will get very similar images in both splits because the images of the same person were taken in a relatively quick succession. At that point you may as well not split it at all and just test on training data (which is bad).

**Comment by rioisme** [comment]
Thanks!
