### ISSUE TITLE
checkpoint file doesn't work

### ISSUE THREAD

**Issue by summer06** [CSAILVision/GazeCapture#8]
I try to load the GazeCapture dataset and use the checkpoint file to test, which sad it can reach L2 error of 2.46cm. But the checkpoint file totally not work and reach the L2 error of about 25cm, I don't know where my problem is, can anybody help? Thanks!!!

**Comment by boxer276** [comment]
I'm having the exact same problem. I use generateCrops.m to generate appleFace, appleLeftEye and appleRightEye folders, and run main.py for test. 
Firstly, the L2 error of the provoded checkpoint is claimed to be 2.46 cm, while the loaded checkpoint file stored an L2 error of 4.51 cm.
Secondly, the predicted errors on the test images are around 25 cm.
Are there any tricks for reproduce the claimed results?

**Comment by erkil1452** [comment]
This and many more new features coming soon in the next update!

The issue is caused by changes in ToTensor() function in pytorch 0.2->0.4. The code was written for 0.2 (as is documented!). The new release will be for 0.4. For now I suggest to change the line ~52 in the ITrackerData.py:
self.meanImg = transforms.ToTensor()(meanImg)
to
self.meanImg = transforms.ToTensor()(meanImg / 255)

**Comment by summer06** [comment]
@Erkil1452 Thank you sooooo much！！It really works！！！

**Comment by boxer276** [comment]
@Erkil1452 Thanks very much for the quick reply, and it works for me too
